### PR TITLE
`v0.8.1`

### LINKED ISSUE #2: custom attribute panicked when using it in a member of a workspace
When using `hs_bindgen` macro in a member of a workspace, it will raise error
```
message: fail to read content of `hsbindgen.toml` configuration file
          n.b. you have to run the command `cargo-cabal` to generate it: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
At this time, the current dir is project root, but `hsbindgen.toml` is generated in member dir. It cause `toml::config()` failed to find `hsbindgen.toml`.

Following is a reproduced project
```
|- Corgo.toml
|- binding-haskell
 |- Cargo.toml
 |- hsbindgen.toml
 |- binding-haskell.cabal
 |- Setup.lhs
 |- src
  |- ...
```
./Cargo.toml
```
[workspace]
members = ["binding-haskell"]

[workspace.package]
...
```
At this project, `toml::config()` will try finding `./hsbindgen.toml`, rather than `./binding-haskell/hsbindgen.toml`.

### PR DESCRIPTION
**Pull request by yvan-sraka**
- Update dependency to `reflexive = 0.4` (previously named `antlion`)

- Fix #2: custom attribute panicked when using it in a member of a workspace

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -48,11 +48,9 @@ pub fn hs_bindgen(attrs: TokenStream, input: TokenStream) -> TokenStream {
     let module = toml::config()
         .default
         .expect("your `hsbindgen.toml` file should contain a `default` field");
-    fs::write(
-        format!("src/{module}.hs"),
-        haskell::template(&module, signatures),
-    )
-    .unwrap_or_else(|_| panic!("fail to write `src/{module}.hs` file"));
+    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(format!("src/{}.hs", module));
```
Comment (silver-ymz) [inline src/lib.rs:51]: Maybe we should use `std::env::var` rather than `env!`. 
`std::env::var` fetches the environment variable at runtime, but `env!` fetches it at compile time. `env!` will replace it with repo cache path like `/Users/silver/.cargo/git/checkouts/hs-bindgen-attribute-cfe9ef1251178c0c/8fb74cb`

File: src/toml.rs [hunk 2]
```diff
@@ -11,17 +11,14 @@ pub(crate) struct Config {
...
 /// Read `hsbindgen.toml` config file generated by `cargo-cabal`
 pub(crate) fn config() -> Config {
-    let config = toml::from_str(
-        &fs::read_to_string("hsbindgen.toml")
-            .or_else(|_| fs::read_to_string(".hsbindgen")) // FIXME: legacy ...
-            .expect(
-                "fail to read content of `hsbindgen.toml` configuration file
+    let cfg = fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("hsbindgen.toml"))
+        .expect(
+            "fail to read content of `hsbindgen.toml` configuration file
```
Comment (silver-ymz) [inline src/toml.rs:16]: Same too.

**Review by silver-ymz — CHANGES_REQUESTED** [review]

**Review by silver-ymz — APPROVED** [review]
Thank you!
